### ISSUE TITLE
document storage profiles

### ISSUE THREAD

**Issue by jan--f** [SUSE/DeepSea#1075]
We should document the format the storage profiles can take. This is mainly to solicit input of what is a valid profile.
```
ceph:
  storage:
    osds:
      /dev/vdb:
        format: bluestore
        wal: /dev/vdc
        wal_size: 200M
        db: /dev/vdc
        db_size: 200
```
