### ISSUE TITLE
ceph.smoketests fails on SLE15 because it can't find an executable "aa-enforce"

### ISSUE THREAD

**Issue by smithfarm** [SUSE/DeepSea#1234]
Environment: SLE15/SES6

How to reproduce: deploy a single-node cluster with MDS and RGW enabled by running Stages 0-4 with default settings. Then do `salt-run state.orch ceph.smoketests`.

The AppArmor smoke tests fail because the orchestration tries to run all the scripts in `/etc/apparmor.d` using an executable called `aa-enforce`, but there is no such executable in the system.

Sample of one of the errors generated:

```
                        ID: aa-enforce /etc/apparmor.d/usr.bin.ceph-mon
                  Function: cmd.run
                    Result: False
                   Comment: Command "aa-enforce /etc/apparmor.d/usr.bin.ceph-mon" run
                   Started: 16:12:23.688331
                  Duration: 13.443 ms
                   Changes:   
                            ----------
                            pid:
                                55667
                            retcode:
                                127
                            stderr:
                                /bin/sh: aa-enforce: command not found
                            stdout:
```
