### ISSUE TITLE
openstack.integrate fails

### ISSUE THREAD

**Issue by hemna** [SUSE/DeepSea#1337]
### Description of Issue/Question
I'm trying to get the openstack.integrate to work.
I had to clone the deepsea git repo and checkout the SES5 branch.  Then I made my own rpm with
'make rpm' and installed the new deepsea rpm.

```
admin:~ # salt-run --out=yaml openstack.integrate
No minions matched the target. No command was sent, no jid was assigned.
No minions matched the target. No command was sent, no jid was assigned.
"Exception occurred in runner openstack.integrate: Traceback (most recent call last):\n
  \ File \"/usr/lib/python2.7/site-packages/salt/client/mixins.py\", line 395, in
  _low\n    data['return'] = self.functions[fun](*args, **kwargs)\n  File \"/srv/modules/runners/openstack.py\",
  line 147, in integrate\n    fsid = _local('pillar.get', ['fsid'])\n  File \"/srv/modules/runners/openstack.py\",
  line 145, in _local\n    return list(local.cmd(master_minion, *args).items())[0][1]\nIndexError:
  list index out of range\n"
```

**Here is the version information**
```admin:~ # salt-run deepsea.version
0.8.5+130.g0514d5ad
admin:~ # rpm -qi salt-minion
Name        : salt-minion
Version     : 2016.11.4
Release     : 46.7.1
Architecture: x86_64
Install Date: Fri Aug 31 09:22:27 2018
Group       : System/Management
Size        : 37807
License     : Apache-2.0
Signature   : RSA/SHA256, Mon Sep 18 04:49:43 2017, Key ID 70af9e8139db7c82
Source RPM  : salt-2016.11.4-46.7.1.src.rpm
Build Date  : Mon Sep 18 04:47:31 2017
Build Host  : sheep70
Relocations : (not relocatable)
Packager    : https://www.suse.com/
Vendor      : SUSE LLC <https://www.suse.com/>
URL         : http://saltstack.org/
Summary     : The client component for Saltstack
Description :
Salt minion is queried and controlled from the master.
Listens to the salt master and execute the commands.
Distribution: SUSE Linux Enterprise 12
admin:~ # rpm -qi salt-master
Name        : salt-master
Version     : 2016.11.4
Release     : 46.7.1
Architecture: x86_64
Install Date: Fri Aug 31 09:22:37 2018
Group       : System/Management
Size        : 1662871
License     : Apache-2.0
Signature   : RSA/SHA256, Mon Sep 18 04:49:43 2017, Key ID 70af9e8139db7c82
Source RPM  : salt-2016.11.4-46.7.1.src.rpm
Build Date  : Mon Sep 18 04:47:31 2017
Build Host  : sheep70
Relocations : (not relocatable)
Packager    : https://www.suse.com/
Vendor      : SUSE LLC <https://www.suse.com/>
URL         : http://saltstack.org/
Summary     : The management component of Saltstack with zmq protocol supported
Description :
The Salt master is the central server to which all minions connect.
Enabled commands to remote systems to be called in parallel rather
than serially.
Distribution: SUSE Linux Enterprise 12
```

**Comment by hemna** [comment]
```admin:~ # salt "*" test.ping
admin.ceph:
    True
mon1.ceph:
    True
data1.ceph:
    True
```

**Comment by hemna** [comment]
```
admin:~ # salt 'admin-public' pillar.get fsid
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
```

**Comment by hemna** [comment]
```
admin:~ # salt '*' pillar.get fsid
mon1.ceph:
    f17750a8-5fbe-3af8-aaba-5da8a0003506
admin.ceph:
    f17750a8-5fbe-3af8-aaba-5da8a0003506
data1.ceph:
    f17750a8-5fbe-3af8-aaba-5da8a0003506
admin:~ # salt 'admin.ceph' pillar.get fsid
admin.ceph:
    f17750a8-5fbe-3af8-aaba-5da8a0003506
```

**Comment by hemna** [comment]
I hacked the /srv/pillar/ceph/master_minion.sls file to contain admin.ceph and I'm getting lots of different errors now.

```
admin:~ # salt-run --out=yaml openstack.integrate
fetched master_minion admin.ceph
ERROR:
- - "Rendering SLS 'base:ceph.openstack.glance.key.default' failed: Jinja error: coercing
    to Unicode: need string or buffer, NoneType found\nTraceback (most recent call
    last):\n  File \"/usr/lib/python2.7/site-packages/salt/utils/templates.py\", line
    368, in render_jinja_tmpl\n    output = template.render(**decoded_context)\n  File
    \"/usr/lib/python2.7/site-packages/jinja2/environment.py\", line 989, in render\n
    \   return self.environment.handle_exception(exc_info, True)\n  File \"/usr/lib/python2.7/site-packages/jinja2/environment.py\",
    line 754, in handle_exception\n    reraise(exc_type, exc_value, tb)\n  File \"<template>\",
    line 13, in top-level template code\n  File \"/var/cache/salt/minion/extmods/modules/keyring.py\",
    line 16, in secret\n    if os.path.exists(filename):\n  File \"/usr/lib64/python2.7/genericpath.py\",
    line 26, in exists\n    os.stat(path)\nTypeError: coercing to Unicode: need string
    or buffer, NoneType found\n\n; line 13\n\n---\n[...]\n    - group: salt\n    -
    mode: 600\n    - makedirs: True\n    - context:\n      client: client.{{ prefix
    }}glance\n      secret: {{ salt['keyring.secret'](keyring_file) }}    <======================\n
    \     prefix: \"{{ prefix }}\"\n    - fire_event: True\n\n\nTraceback (most recent
    call last):\n[...]\n---"
  - "Detected conflicting IDs, SLS IDs need to be globally unique.\n    The conflicting
    ID is 'auth None' and is found in SLS 'base:ceph.openstack.glance.auth.default'
    and SLS 'base:ceph.openstack.cinder.auth.default'"
  - "Rendering SLS 'base:ceph.openstack.cinder.key.default' failed: Jinja error: coercing
    to Unicode: need string or buffer, NoneType found\nTraceback (most recent call
    last):\n  File \"/usr/lib/python2.7/site-packages/salt/utils/templates.py\", line
    368, in render_jinja_tmpl\n    output = template.render(**decoded_context)\n  File
    \"/usr/lib/python2.7/site-packages/jinja2/environment.py\", line 989, in render\n
    \   return self.environment.handle_exception(exc_info, True)\n  File \"/usr/lib/python2.7/site-packages/jinja2/environment.py\",
    line 754, in handle_exception\n    reraise(exc_type, exc_value, tb)\n  File \"<template>\",
    line 13, in top-level template code\n  File \"/var/cache/salt/minion/extmods/modules/keyring.py\",
    line 16, in secret\n    if os.path.exists(filename):\n  File \"/usr/lib64/python2.7/genericpath.py\",
    line 26, in exists\n    os.stat(path)\nTypeError: coercing to Unicode: need string
    or buffer, NoneType found\n\n; line 13\n\n---\n[...]\n    - group: salt\n    -
    mode: 600\n    - makedirs: True\n    - context:\n      client: client.{{ prefix
    }}cinder\n      secret: {{ salt['keyring.secret'](keyring_file) }}    <======================\n
    \     prefix: \"{{ prefix }}\"\n    - fire_event: True\n\n\nTraceback (most recent
    call last):\n[...]\n---"
  - "Detected conflicting IDs, SLS IDs need to be globally unique.\n    The conflicting
    ID is 'auth None' and is found in SLS 'base:ceph.openstack.cinder.auth.default'
    and SLS 'base:ceph.openstack.cinder-backup.auth.default'"
  - "Rendering SLS 'base:ceph.openstack.cinder-backup.key.default' failed: Jinja error:
    coercing to Unicode: need string or buffer, NoneType found\nTraceback (most recent
    call last):\n  File \"/usr/lib/python2.7/site-packages/salt/utils/templates.py\",
    line 368, in render_jinja_tmpl\n    output = template.render(**decoded_context)\n
    \ File \"/usr/lib/python2.7/site-packages/jinja2/environment.py\", line 989, in
    render\n    return self.environment.handle_exception(exc_info, True)\n  File \"/usr/lib/python2.7/site-packages/jinja2/environment.py\",
    line 754, in handle_exception\n    reraise(exc_type, exc_value, tb)\n  File \"<template>\",
    line 13, in top-level template code\n  File \"/var/cache/salt/minion/extmods/modules/keyring.py\",
    line 16, in secret\n    if os.path.exists(filename):\n  File \"/usr/lib64/python2.7/genericpath.py\",
    line 26, in exists\n    os.stat(path)\nTypeError: coercing to Unicode: need string
    or buffer, NoneType found\n\n; line 13\n\n---\n[...]\n    - group: salt\n    -
    mode: 600\n    - makedirs: True\n    - context:\n      client: client.{{ prefix
    }}cinder-backup\n      secret: {{ salt['keyring.secret'](keyring_file) }}    <======================\n
    \     prefix: \"{{ prefix }}\"\n    - fire_event: True\n\n\nTraceback (most recent
    call last):\n[...]\n---"
```

**Comment by hemna** [comment]
```
admin:~ # salt 'admin.ceph' state.apply ceph.openstack
admin.ceph:
    Data failed to compile:
----------
    Rendering SLS 'base:ceph.openstack.glance.key.default' failed: Jinja error: coercing to Unicode: need string or buffer, NoneType found
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 368, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 13, in top-level template code
  File "/var/cache/salt/minion/extmods/modules/keyring.py", line 16, in secret
    if os.path.exists(filename):
  File "/usr/lib64/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found

; line 13

---
[...]
    - group: salt
    - mode: 600
    - makedirs: True
    - context:
      client: client.{{ prefix }}glance
      secret: {{ salt['keyring.secret'](keyring_file) }}    <======================
      prefix: "{{ prefix }}"
    - fire_event: True
```

**Comment by tserong** [comment]
What does `salt admin.ceph keyring.file glance2 ''` give? (yes, that's an empty quoted string at the end). It should result in:

````
admin.ceph:
    /srv/salt/ceph/openstack/cache/glance.keyring
````

If you get None, I wonder if the latest version of the keyring module isn't sync'd? Does `salt '*' saltutil.sync_all` help?

**Comment by hemna** [comment]
```
admin:~ # salt admin.ceph keyring.file glance ''
admin.ceph:
    None
admin:~ # salt '*' saltutil.sync_all
admin.ceph:
    ----------
    beacons:
    engines:
    grains:
    log_handlers:
    modules:
        - modules.cephdisks
        - modules.cephinspector
        - modules.keyring
        - modules.osd
        - modules.proposal
        - modules.wait
    output:
    proxymodules:
    renderers:
    returners:
    sdb:
    states:
        - states.osd
    utils:
mon1.ceph:
    ----------
    beacons:
    engines:
    grains:
    log_handlers:
    modules:
        - modules.cephdisks
        - modules.cephinspector
        - modules.keyring
        - modules.osd
        - modules.proposal
        - modules.wait
    output:
    proxymodules:
    renderers:
    returners:
    sdb:
    states:
        - states.osd
    utils:
data1.ceph:
    ----------
    beacons:
    engines:
    grains:
    log_handlers:
    modules:
        - modules.cephdisks
        - modules.cephinspector
        - modules.keyring
        - modules.osd
        - modules.proposal
        - modules.wait
    output:
    proxymodules:
    renderers:
    returners:
    sdb:
    states:
        - states.osd
    utils:
admin:~ # salt admin.ceph keyring.file glance ''
admin.ceph:
    /srv/salt/ceph/openstack/cache/glance.keyring
```

**Comment by hemna** [comment]
```
ceph_conf:
  cluster_network: 172.16.2.0/24
  fsid: f17750a8-5fbe-3af8-aaba-5da8a0003506
  mon_host: 172.16.1.11
  mon_initial_members: mon1
  public_network: 172.16.1.0/24
cinder:
  key: AQCngpJbAAAAABAAMEfO7KbtQxVt2gKmYIdYSA==
  rbd_store_pool: cloud-volumes
  rbd_store_user: cinder
cinder-backup:
  key: AQCngpJbAAAAABAA3n6NIV32YbRBgIzVodFIpQ==
  rbd_store_pool: cloud-backups
  rbd_store_user: cinder-backup
glance:
  key: AQCngpJbAAAAABAArtzGYHXN/7XitiN9ywJ0LA==
  rbd_store_pool: cloud-images
  rbd_store_user: glance
nova:
  rbd_store_pool: cloud-vms
radosgw_urls: []
```
