### ISSUE TITLE
default rgw system user missing

### ISSUE THREAD

**Issue by swiftgist** [SUSE/DeepSea#314]
We should really include the system user in the DeepSea configuration.  Otherwise, the admin must research/guess what to put where.  As a workaround, anyone can add the following to /srv/pillar/ceph/stack/ceph/cluster.yml:

```
rgw_configurations:
  rgw:
    users:
      - { uid: "admin", name: "Admin", email: "admin@demo.nil", system: True }
```

prior to running Stage 2.  (Or add this to the pillar and run Stages 2-4.)  A cached version of the system user will appear in /srv/salt/ceph/rgw/cache/user.admin.json.  The rgw salt module does this.  When openATTIC starts, the same credentials are retrieved by the ui_rgw runner.

The permanent entry needs to end up in /srv/pillar/ceph/stack/ceph/default/cluster.yml which comes from the populate runner.
