### ISSUE TITLE
How to use deepsea to set the journal_size？

### ISSUE THREAD

**Issue by akumacxd** [SUSE/DeepSea#396]
HI

How to use deepsea to set the journal_size？
 The default journal_size of ceph  is 5G，so if I want to make it bigger , how to set ?
 In addition, I want to use SSD as a journal disk, and the data disk is SATA，how to set ?

**Comment by akumacxd** [comment]
Whether to modify the following salt configuration file ?
# cat osd/partition/default.sls 

{% for device in salt['pillar.get']('storage:osds') %}
{{ device }} journal:
  module.run:
    - name: partition.mkpart
    - device: {{ device }}
    - part_type: primary
    - start: 0%
    - end: 10%
    - require:
      - module: {{ device }} label
    - unless: stat {{ device }}1

{{ device }} journal uuid:
  cmd.run:
    - name: "sgdisk -t 1:45b0969e-9b03-4f30-b4c6-b4b80ceff106 {{ device }}"
    - unless: "sgdisk -i 1 {{ device }} | grep -q unique.*45b0969e-9b03-4f30-b4c6-b4b80ceff106$"

{{ device }} data:
  module.run:
    - name: partition.mkpart
    - device: {{ device }}
    - part_type: primary
    - start: 10%
    - end: 100%
    - require:
      - module: {{ device }} label
    - unless: stat {{ device }}2

{{ device }} uuid:
  cmd.run:
    - name: "sgdisk -t 2:4fbd7e29-9d25-41b8-afd0-062c0ceff05d {{ device }}"
    - unless: "sgdisk -i 2 {{ device }} | grep -q unique.*4fbd7e29-9d25-41b8-afd0-062c0ceff05d"

{{ device }} label:
  module.run:
    - name: partition.mklabel
    - device: {{ device }}
    - label_type: gpt
    - unless: blkid {{ device }} 

{% endfor %}

**Comment by jschmid1** [comment]
Deepsea is currently switching over to a different proposal structure and proposal-generating approach, which will allow you to set the journal_size per osd.

You can give it a try by running:

``` salt-run proposal.populate```

there is also: ``` salt-run proposal.peek``` which gives you a preview of the configuration that would've been written.

In your example you'd write

``` salt-run proposal.populate format=filestore journal_size=10G ```

to get the help page

``` salt-run proposal.help ```

Make sure to update your policy.cfg with the newly generated profile-<name>.
And as it's not the default it does not overwrite your current 'profile-*', so you should delete/move it before.

That is only included if you are using the current master (or at least have a version with 8fa496a4daaed374cbb0655c1f22ba851a4dc9c7 included )

**Comment by akumacxd** [comment]
thankn you for you reply, but not support ?
admin:~ # salt-run proposal.help
'proposal.help' is not available.

SUSE12SP2 + Storage4:
admin:~ # rpm -qa deepsea
deepsea-0.6.10-1.3.noarch

**Comment by akumacxd** [comment]
if I change SUSE12SP3 +Storage5 , is it support ?

**Comment by swiftgist** [comment]
Yes, the latest milestone contains DeepSea 0.7.15.  The osd/partition/default.sls has been integrated into a Salt module so there's no need to customize that file.  With the new module, a different yaml format is supported as well.  Here is an example:

```
ceph:
  storage:
    osds:
      /dev/disk/by-id/ata-INTEL_SSDSC2BA400G4_BTHV6082036F400NGN:
        encryption: ''
        format: filestore
        journal: /dev/disk/by-id/nvme-SNVMe_INTEL_SSDPEDMD80CVFT6075000C800CGN
        journal_size: 5G
      /dev/disk/by-id/ata-INTEL_SSDSC2BA400G4_BTHV6082036H400NGN:
        encryption: ''
        format: filestore
        journal: /dev/disk/by-id/nvme-SNVMe_INTEL_SSDPEDMD80CVFT6075000C800CGN
        journal_size: 5G
      /dev/disk/by-id/ata-INTEL_SSDSC2BA400G4_BTHV6082036R400NGN:
        encryption: ''
        format: filestore
        journal: /dev/disk/by-id/nvme-SNVMe_INTEL_SSDPEDMD80CVFT54700076800CGN
        journal_size: 5G
      /dev/disk/by-id/ata-INTEL_SSDSC2BA400G4_BTHV608203EY400NGN:
        encryption: ''
        format: filestore
        journal: /dev/disk/by-id/nvme-SNVMe_INTEL_SSDPEDMD80CVFT6075000C800CGN
        journal_size: 5G
      /dev/disk/by-id/ata-INTEL_SSDSC2BA400G4_BTHV608300WC400NGN:
        encryption: ''
        format: filestore
        journal: /dev/disk/by-id/nvme-SNVMe_INTEL_SSDPEDMD80CVFT54700076800CGN
        journal_size: 5G
      /dev/disk/by-id/ata-INTEL_SSDSC2BA400G4_BTHV611201F3400NGN:
        encryption: ''
        format: filestore
        journal: /dev/disk/by-id/nvme-SNVMe_INTEL_SSDPEDMD80CVFT54700076800CGN
        journal_size: 5G
```

Note the two space indentation of each of the keywords and the space following the colon on the OSD attributes.  

With the latest version and a little practice, give `salt-run proposal.help` a try to save yourself significant typing.  Also, note the uppercase G for the size.  I added support for either case in https://github.com/SUSE/DeepSea/commit/ff431a1ae22c61a5d19ed9d71e139838a8de9c47, but that was two days ago.

Once you have created your desired profile(s) for your servers, add them to your policy.cfg.  Be sure to remove any existing hardware profiles (i.e. profile-*) from the policy.cfg.  If two profiles include the same device, expect to get an error of "Conflicting IDs".

**Comment by akumacxd** [comment]
SUSE12SP3+Storage5：
I modified the journal_size parameter why is it always the 100M data disk, 19G log disk? 
Do I need to add additional parameters? 
 # lsblk 
NAME            MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0             7:0    0   1.4G  1 loop /mnt/storage5
loop1             7:1    0 488.3M  1 loop /mnt/milestone7
sda               8:0    0    40G  0 disk 
├─sda1            8:1    0     1G  0 part /boot
└─sda2            8:2    0    39G  0 part 
  ├─vg00-lvswap 254:0    0     2G  0 lvm  [SWAP]
  └─vg00-lvroot 254:1    0    37G  0 lvm  /
**sdb               8:16   0    20G  0 disk 
├─sdb1            8:17   0   100M  0 part /var/lib/ceph/tmp/mnt.ux6gdo
└─sdb2            8:18   0  19.9G  0 part** 
sdc               8:32   0    20G  0 disk 
sr0              11:0    1   3.2G  0 rom

# salt-run proposal.populate journal_size=10G
{}
True

# vim /srv/pillar/ceph/proposals/policy.cfg
 # Cluster assignment
 cluster-ceph/cluster/*.example.com.sls
 
 # Hardware Profile
 #profile-*-1/cluster/*.sls
 #profile-*-1/stack/default/ceph/minions/*.yml
 profile-1VMware,10GB-2VMware,20GB-1/cluster/*.sls
 profile-1VMware,10GB-2VMware,20GB-1/stack/default/ceph/minions/*.yml
 
 profile-default/cluster/*.sls
 profile-default/stack/default/ceph/minions/*.yml
 
 # Common configuration
 config/stack/default/global.yml
 config/stack/default/ceph/cluster.yml
 
 # Role assignment
 ## Roles
 # Master
 role-master/cluster/admin*.sls
 
 # ADMIN
 role-admin/cluster/admin*.sls
 
 # MON
 role-mon/stack/default/ceph/minions/node00*.yml
 role-mon/cluster/node00*.sls

**Comment by jschmid1** [comment]
The following disk partition scheme is only temporary as ceph creates the OSD.

> sdb 8:16 0 20G 0 disk
├─sdb1 8:17 0 100M 0 part /var/lib/ceph/tmp/mnt.ux6gdo
└─sdb2 8:18 0 19.9G 0 part

You successfully ran `salt-run proposal.populate journal_size=10G`

So could you paste the output of 

> /srv/pillar/ceph/proposals/profile-default/stack/default/ceph/minions/*.yml

Regarding the sections:

> Cluster assignment
> cluster-ceph/cluster/*.example.com.sls

Are  you sure that the expression '*.example.com.sls' matches any hosts?

It also look like you don't match nodes in your 'profile section'

> Hardware Profile
> profile-1VMware,10GB-2VMware,20GB-1/stack/default/ceph/minions/.yml
> profile-default/cluster/.sls
> profile-default/stack/default/ceph/minions/.yml

Make sure to only include *1* profile (profile-1VMWare.. _OR_ profile-default..). Also make sure that the expression you are using matches the files in the subdirectories. An example which will most likely work.

> profile-default/stack/default/ceph/minions/*.yml

Note the asterisk between minions/ and .yml

**Comment by akumacxd** [comment]
salt-run proposal.populate journal_size=10G name=test001
{}
True

ll profile-test001/
.filter  cluster/ stack/   

cat profile-test001/.filter 
'*':
  data: 0
  db-ratio: 5
  db-size: 500m
  encryption: ''
  format: bluestore
  journal: 0
  journal-size: 5g
  journal_size: 10G
  leftovers: false
  name: test001
  nvme-spinner: false
  nvme-ssd: false
  nvme-ssd-spinner: false
  ratio: 5
  ssd-spinner: false
  standalone: false
  wal: 0
  wal-size: 500m

ll profile-test001/cluster/
total 12
-rw-r--r-- 1 salt salt 17 Jul  3 16:44 node001.example.com.sls
-rw-r--r-- 1 salt salt 17 Jul  3 16:44 node002.example.com.sls
-rw-r--r-- 1 salt salt 17 Jul  3 16:44 node003.example.com.sls  
  
ll profile-test001/stack/default/ceph/minions/
total 12
-rw-r--r-- 1 salt salt 164 Jul  3 16:44 node001.example.com.yml
-rw-r--r-- 1 salt salt 164 Jul  3 16:44 node002.example.com.yml
-rw-r--r-- 1 salt salt 164 Jul  3 16:44 node003.example.com.yml 
  
cat profile-test001/stack/default/ceph/minions/node001.example.com.yml 
ceph:
  storage:
    osds:
      /dev/sdb:
        db: ''
        db_size: 500m
        encryption: ''
        format: bluestore
        wal: ''
        wal_size: 500m
      /dev/sdc:
        db: ''
        db_size: 500m
        encryption: ''
        format: bluestore
        wal: ''
        wal_size: 500m

vim /srv/pillar/ceph/proposals/policy.cfg
# Cluster assignment
cluster-ceph/cluster/*.example.com.sls

# Hardware Profile
profile-test001/cluster/*.sls
profile-test001/stack/default/ceph/minions/*.yml

# Common configuration
config/stack/default/global.yml
config/stack/default/ceph/cluster.yml

# Role assignment
## Roles
# Master
role-master/cluster/admin*.sls

# ADMIN
role-admin/cluster/admin*.sls

# MON
role-mon/stack/default/ceph/minions/node00*.yml
role-mon/cluster/node00*.sls

# salt-run state.orch ceph.stage.2
# salt '*' saltutil.pillar_refresh
# salt '*' pillar.items
sed -i 's/if (not self.in_dev_env and len(storage) < 4/if (not self.in_dev_env and len(storage) < 2/g' /srv/modules/runners/validate.py
# salt-run state.orch ceph.stage.3

**Comment by akumacxd** [comment]
lsblk 
NAME            MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0             7:0    0 488.3M  1 loop /mnt/milestone7
loop1             7:1    0   1.4G  1 loop /mnt/storage5
sda               8:0    0    40G  0 disk 
├─sda1            8:1    0     1G  0 part /boot
└─sda2            8:2    0    39G  0 part 
  ├─vg00-lvswap 254:0    0     2G  0 lvm  [SWAP]
  └─vg00-lvroot 254:1    0    37G  0 lvm  /
sdb               8:16   0    20G  0 disk 
├─sdb1            8:17   0   100M  0 part /var/lib/ceph/osd/ceph-2
└─sdb2            8:18   0  19.9G  0 part 
sdc               8:32   0    20G  0 disk 
├─sdc1            8:33   0   100M  0 part /var/lib/ceph/osd/ceph-5
└─sdc2            8:34   0  19.9G  0 part 
sr0              11:0    1   3.2G  0 rom

**Comment by akumacxd** [comment]
>salt 'node001*' pillar.items
node001.example.com:
    ----------
    available_roles:
        - storage
        - admin
        - mon
        - mds
        - igw
        - openattic
        - rgw
        - ganesha
        - client-cephfs
        - client-radosgw
        - client-iscsi
        - client-nfs
        - master
    benchmark:
        ----------
        default-collection:
            simple.yml
        job-file-directory:
            /run/cephfs_bench_jobs
        log-file-directory:
            /var/log/cephfs_bench_logs
        work-directory:
            /run/cephfs_bench
    ceph:
        ----------
        storage:
            ----------
            osds:
                ----------
                /dev/sdb:
                    ----------
                    db:
                    db_size:
                        500m
                    encryption:
                    format:
                        bluestore
                    wal:
                    wal_size:
                        500m
                /dev/sdc:
                    ----------
                    db:
                    db_size:
                        500m
                    encryption:
                    format:
                        bluestore
                    wal:
                    wal_size:
                        500m
    cluster:
        ceph
    cluster_network:
        192.168.3.0/24
    fsid:
        9a42283d-3565-3ea2-8e27-7b0919929123
    master_minion:
        admin.example.com
    mon_host:
        - 192.168.2.122
        - 192.168.2.123
        - 192.168.2.121
    mon_initial_members:
        - node002
        - node003
        - node001
    public_address:
        192.168.2.121
    public_network:
        192.168.2.0/24
    roles:
        - storage
        - mon
    time_init:
        ntp
    time_server:
        admin.example.com
==============================================================

**Comment by jschmid1** [comment]
That looks better!

You still asked proposal.populate to create bluestore OSDs. By design there is not 'journal' on bluestore devices. If you are not familiar with the new format, I'd suggest you to look Sage's presentation.

https://de.slideshare.net/sageweil1/bluestore-a-new-storage-backend-for-ceph-one-year-in

If you still want to deploy filestore, just appends a argument, like this:

`rm -rf profile-test001`
`salt-run proposal.populate journal_size=10G name=test001 format=filestore`

**Comment by akumacxd** [comment]
@jschmid1 
You mean the above configuration is good ？
filesotre is use journal ,  bluestore is not use journal

According to the slide,my understanding is as follows :
             ObjectStore
-------------------------------------------
 data                      metadata
    |                        rocksDB
    |                        blueRocksEnv
    |                           BlueFS
    |                          |                 |
blockdevice     blockdevice  blockdevice

sdb 8:16 0 20G 0 disk
├─sdb1 8:17 0 100M 0 part /var/lib/ceph/osd/ceph-2    **<====== metadata**
└─sdb2 8:18 0 19.9G 0 part                                              **<====== data**（raw device）
sdc 8:32 0 20G 0 disk
├─sdc1 8:33 0 100M 0 part /var/lib/ceph/osd/ceph-5     <====== metadata
└─sdc2 8:34 0 19.9G 0 part                                              <====== data
is it right?

**Comment by akumacxd** [comment]
@jschmid1 
     I have another question. How do I put DB on SSD or nvme ? 
     If I have 4 SATA Disk and one NVME SSD on one node

**Comment by jschmid1** [comment]
>sdb 8:16 0 20G 0 disk
>├─sdb1 8:17 0 100M 0 part /var/lib/ceph/osd/ceph-2 <===== metadata （rocks DB ...）
>└─sdb2 8:18 0 19.9G 0 part <===== data（raw device）
> is it right?

yes.

> I have another question. How do I put DB on SSD or nvme ?
> If I have 4 SATA Disk and one NVME SSD on one node

You can either leverage the `.help` of `proposal` (which I'd suggest in case you want to avoid manual editing) or manually edit the config under:

`profile-test001/stack/default/ceph/minions/*.yml`

to look something like:

```yaml
ceph:
  storage:
    osds:
      /dev/sdb:
        db: /dev/<your_ssd_that_should_be_used_as_db>
        db_size: 500m
        format: bluestore
        wal: /dev/<if_you_want_an_external_wal_also>
        wal_size: 500m
```
