### ISSUE TITLE
Bluestore reusing db/wal in certain circumstances

### ISSUE THREAD

**Issue by jschmid1** [SUSE/DeepSea#441]
Usually we except to have a new 'highest partition' when defining a external osd.wal or/and osd.db. But due to [_bluestore_partitions()](https://github.com/SUSE/DeepSea/blob/master/srv/salt/_modules/osd.py#L796) we skip the creation when no size is defined (find out why).
The issue here is that we will have [is_partitioned](https://github.com/SUSE/DeepSea/blob/master/srv/salt/_modules/osd.py#L1045) retuning true when you happen to have at least one bluestore OSD that _has_ a db_size or wal_size defined. This triggers a partition-creation on the wal/db device which is then also picked up by a bluestore osd that hasn't defined a wal/db_size but a wal/db. Essentially you end up with 2 partitions that are used by multiple bluestore OSDs.

```yaml
ceph:
  storage:
    osds:
      /dev/vdc: <- will create two partitions on /dev/vdf
        encryption: ''
        format: bluestore
        wal: /dev/vdf
        db: /dev/vdf
        wal_size: 1G
        db_size: 1G
      /dev/vdd: <- will also use those two partitions created by /dev/vdc
        encryption: ''
        format: bluestore
        wal: /dev/vdf
        db: /dev/vdf

```
