### ISSUE TITLE
Provide an option to return the DeepSea version via cli / REST API

### ISSUE THREAD

**Issue by LenzGr** [SUSE/DeepSea#511]
openATTIC currently simply assumes that it's communicating with an up to date version of DeepSea when it submits API requests. As DS is installed on the Salt master node, it's not easily possible to ensure that a certain version of DeepSea is installed as required by openATTIC (e.g. using RPM dependencies during installation).

It would be useful if the DeepSea version number could be obtained via an API call, so oA could properly check the version requirements and bail out gracefully, if the DS version is too old (currently, it would likely simply fail with obscure errors).

**Comment by LenzGr** [comment]
FWIW, this is the corresponding openATTIC issue: [OP-2543](https://tracker.openattic.org/browse/OP-2543)

**Comment by swiftgist** [comment]
Since master_minion is defined in the pillar, the command

```
# salt 'master_minion' pkg.version deepsea
admin.ceph:
    0.7.19-0
```

I would suggest splitting on both '-' and '+' since the short git sha will be concatenated for some packages.

**Comment by smithfarm** [comment]
`salt --static --out json . . .` might produce more readily parseable output?

**Comment by swiftgist** [comment]
openATTIC needs to use the salt-api but the json output may be automatic at that point.

**Comment by LenzGr** [comment]
@swiftgist if this information could also be obtained via the SALT REST API, this should suffice. But I'd like to get @rjfd and @sebastian-philipp take on that.

**Comment by sebastian-philipp** [comment]
Should be doable to integrate this into oA, as long as it's queryable.

**Comment by swiftgist** [comment]
Here's one example:

```
# curl -sk http://localhost:8000/login -H 'Accept: application/x-yaml' -d username=admin -d sharedsecret=d169e58c-2640-4736-819f-00b89691f691 -d eauth=sharedsecret
return:
- eauth: sharedsecret
  expire: 1505865693.076882
  perms:
  - .*
  - '@runner'
  - '@wheel'
  start: 1505822493.076881
  token: 922a5e965f121d6359527167ebb6d8781df1bf66
  user: admin

# curl -sSk http://localhost:8000 -H 'Accept: application/x-yaml' -d username=admin -H 'X-Auth-Token: 922a5e965f121d6359527167ebb6d8781df1bf66' -d client=local -d tgt='admin.ceph' -d fun=pkg.version -d arg=deepsea
return:
- admin.ceph: 0.7.27-0
```

Since the functionality is already there in Salt, I'll close this.
