### ISSUE TITLE
ntp client configuration

### ISSUE THREAD

**Issue by swiftgist** [SUSE/DeepSea#91]
DeepSea currently forces synchronization, but does not write an ntp.conf to the minions.  The request is to add the client configuration.

**Comment by BlaineEXE** [comment]
Trying to develop some requirements/clarity here, as I'm not 100% sure how to implement, as there are many avenues open to me.

As I understand it, the current implementation enables NTP and sets the NTP server master to the Salt master.

It's my understanding we want to take a user-specified ntp.conf file and distribute it to all nodes, but we must avoid distributing the file to the node that is the ntp master. Yes?
If this is the case:

1) Where should DeepSea get the ntp.conf file? In the `srv/salt/ceph/time/ntp/conf_file` directory, perhaps? Should we populate a default ntp.conf file here, or should we fall back to the existing method of setting the NTP server master to the Salt master?

2) Speaking of falling back, what if the user doesn't want to specify an ntp.conf and wants to use the existing method instead? What is the preferred method for the customer to provide this input? I have a thought to do as @rjfd has done in in his branch https://github.com/rjfd/DeepSea/blob/wip-single-config/srv/pillar/ceph/config.sls and create  cluster-level config file where the user could specify, for example:
```yaml
cluster_config:
  # If the 'ntp' section is configured, DeepSea will manage the cluster's NTP configuration
  # If this section is not configured, DeepSea will not manage the cluster's NTP configuration
  # Note that Ceph requires NTP to be configured to operate properly
  ntp:
    # Distribute an NTP configuration file given at the following path to all nodes
    distribute_ntp_conf_file: /path/to/conf/file
    # If the path is not given, configure the node given as the NTP master
    # Recommended NTP master is the Salt master node
    ntp_master: ceph.admin
```
